### ISSUE TITLE
Failed to build according to build instructions

### ISSUE THREAD

**Issue by dobbse42** [lucasberent/qecc#1]
The pre-built wheels are not available (i.e. running pip install mqt.qecc errors with "no matching distribution found").

When skipping this step and just trying to clone the repo according to the later instructions (git clone --recurse-submodules -j8 https://github.com/lucasberent/qecc) the clone fails halfway through with the message "clone of 'git@github.com/nlohmann/json.git' failed.

**Comment by burgholzer** [comment]
Thanks for reaching out. Indeed, the pre-built wheels for the project are not yet available. Expect them to be released soon!

Regarding building from source: the issue you are facing is most likely due to no SSH key/config being set up for your git client and GitHub connection. If you want a real quick fix, then properly setup an SSH key with GitHub as described e.g. in https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
I'll submit a PR that removes this requirement for cloning later today.

**Comment by burgholzer** [comment]
Just pushed the change. You should now be able to properly clone the project even without an SSH key set up.
Just clone the project and execute `pip install --editable .` to install the Python package.

Feel free to reopen this issue if you should face any further problems!
